@startuml

skinparam classAttributeIconSize 0

' ---------------------------
' Client MVC
' ---------------------------
package "Client MVC" {
  class ClientModel {
    - clientID : int
    - name : String
    - email : String
    - password : String
    - type : String
    - age : int
  }

  class ClientView {
    + displayClientInfo(client: ClientModel) : void
    + getClientInput() : Map
  }

  class ClientController {
    + createClient(data: Map) : void
    + updateClient(data: Map) : void
    + deleteClient(id: int) : void
  }

  ClientController ..> ClientModel : uses
  ClientController ..> ClientView : interacts with
}
@enduml